name: ClashForge

on:
  push:
    paths-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run_demo_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.10'

      - name: Install requirements.txt
        run: |
          pip install -r ./requirements.txt

      - name: Run ClashForge.py
        run: python ClashForge.py

      - name: Upload clash_config.yaml to Gist
        run: |
          # 检查文件是否存在
          if [ -f clash_config.yaml ]; then
            # 读取 YAML 文件的内容
            content=$(<clash_config.yaml)

            # 使用 curl 上传到 Gist
            curl -X POST -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/gists \
              -d '{
                    "description": "ClashForge config file",
                    "public": false,
                    "files": {
                      "clash_config.yaml": {
                        "content": "'"$content"'"
                      }
                    }
                  }'
          else
            echo "clash_config.yaml does not exist, skipping upload."
          fi
